"use client";

import { useState } from "react";
import { CaretDown, Prohibit, SealCheck, Spinner } from "@phosphor-icons/react";
import { useMatchReport, type MatchCandidate } from "@/lib/businessNetwork";
import { formatMoney } from "@/lib/money";

/**
 * Shows the buyer how their shortlist was produced: the criteria, every
 * candidate's points per criterion, who was invited, who answered, who was
 * ruled out and why, and the audit events behind it.
 *
 * The report is generated by the same deterministic scorer that sent the
 * invitations, so this is the real ranking rather than a summary of it.
 */
export default function MatchConsole({ rfqId }: { rfqId: number }) {
  const report = useMatchReport(rfqId);
  const [expanded, setExpanded] = useState<number | null>(null);

  if (report.isLoading) {
    return (
      <div className="flex items-center gap-2 p-6 text-[0.85rem] text-[var(--text-muted)]">
        <Spinner size={16} className="animate-spin" /> Recomputing the supplier ranking
      </div>
    );
  }

  if (!report.data) {
    return (
      <p className="p-6 text-[0.85rem] text-[var(--text-secondary)]">
        The match report is not available for this request.
      </p>
    );
  }

  const { criteria, candidates, shortlisted, excluded, funnel, maxScore, inviteLimit, events } = report.data;

  return (
    <div>
      <div className="grid grid-cols-2 gap-px border-b border-[var(--b-line)] bg-[var(--b-line)] sm:grid-cols-5">
        <FunnelCell label="Invited" value={funnel.invited} />
        <FunnelCell label="Viewed" value={funnel.viewed} />
        <FunnelCell label="Quoted" value={funnel.quoted} />
        <FunnelCell label="Declined" value={funnel.declined} />
        <FunnelCell label="Awarded" value={funnel.awarded} />
      </div>

      <div className="px-5 py-4">
        <p className="text-[0.8rem] text-[var(--text-secondary)]">
          {candidates.length} eligible {candidates.length === 1 ? "supplier" : "suppliers"} scored out of {maxScore}.
          The top {inviteLimit} are invited automatically; ties break by least recently invited.
        </p>

        <ul className="mt-3 flex flex-wrap gap-1.5">
          {criteria.map((criterion) => (
            <li key={criterion.key} className="b-chip">
              {criterion.label}
              <span className="font-[family-name:var(--font-mono)] text-[var(--text-muted)]">{criterion.max}</span>
            </li>
          ))}
        </ul>
      </div>

      {candidates.length ? (
        <ul className="border-t border-[var(--b-line)]">
          {candidates.map((candidate, index) => (
            <CandidateRow
              key={candidate.vendorId}
              candidate={candidate}
              rank={index + 1}
              maxScore={maxScore}
              shortlisted={shortlisted.includes(candidate.vendorId)}
              expanded={expanded === candidate.vendorId}
              onToggle={() => setExpanded(expanded === candidate.vendorId ? null : candidate.vendorId)}
            />
          ))}
        </ul>
      ) : (
        <p className="border-t border-[var(--b-line)] px-5 py-6 text-[0.85rem] text-[var(--text-secondary)]">
          No supplier is currently eligible for this requirement. Operations has been notified to source manually.
        </p>
      )}

      {excluded.length ? (
        <details className="border-t border-[var(--b-line)]">
          <summary className="cursor-pointer list-none px-5 py-3.5 text-[0.82rem] font-semibold text-[var(--text-secondary)] hover:bg-[var(--b-tint)]">
            {excluded.length} {excluded.length === 1 ? "supplier was" : "suppliers were"} ruled out
          </summary>
          <ul className="px-5 pb-4">
            {excluded.map((exclusion) => (
              <li
                key={exclusion.vendorId}
                className="flex items-start gap-2 border-t border-[var(--b-line)] py-2.5 text-[0.8rem] first:border-0"
              >
                <Prohibit size={14} className="mt-0.5 shrink-0 text-[var(--text-muted)]" />
                <span className="text-[var(--text-secondary)]">
                  <span className="font-semibold text-[var(--text-primary)]">{exclusion.vendorName}</span>
                  {" — "}
                  {exclusion.reason}
                </span>
              </li>
            ))}
          </ul>
        </details>
      ) : null}

      {events.length ? (
        <details className="border-t border-[var(--b-line)]">
          <summary className="cursor-pointer list-none px-5 py-3.5 text-[0.82rem] font-semibold text-[var(--text-secondary)] hover:bg-[var(--b-tint)]">
            Audit trail ({events.length})
          </summary>
          <ol className="px-5 pb-4">
            {events.map((event, index) => (
              <li
                key={`${event.event}-${index}`}
                className="flex items-baseline justify-between gap-3 border-t border-[var(--b-line)] py-2.5 text-[0.78rem] first:border-0"
              >
                <span className="font-[family-name:var(--font-mono)] text-[var(--text-primary)]">{event.event}</span>
                <span className="shrink-0 text-[var(--text-muted)]">{new Date(event.occurredAt).toLocaleString()}</span>
              </li>
            ))}
          </ol>
        </details>
      ) : null}
    </div>
  );
}

function CandidateRow({
  candidate,
  rank,
  maxScore,
  shortlisted,
  expanded,
  onToggle,
}: {
  candidate: MatchCandidate;
  rank: number;
  maxScore: number;
  shortlisted: boolean;
  expanded: boolean;
  onToggle: () => void;
}) {
  const percentage = Math.round((candidate.score / maxScore) * 100);

  return (
    <li className="border-b border-[var(--b-line)] last:border-0">
      <button
        onClick={onToggle}
        aria-expanded={expanded}
        className="flex w-full cursor-pointer items-center gap-4 px-5 py-3.5 text-left transition-colors hover:bg-[var(--b-tint)]"
      >
        <span className="w-6 shrink-0 font-[family-name:var(--font-mono)] text-[0.78rem] text-[var(--text-muted)]">
          {rank}
        </span>

        <span className="min-w-0 flex-1">
          <span className="flex flex-wrap items-center gap-2">
            <span className="truncate text-[0.9rem] font-semibold text-[var(--text-primary)]">
              {candidate.vendorName}
            </span>
            {candidate.verified ? (
              <span className="b-chip b-chip-verified">
                <SealCheck size={11} weight="fill" /> Verified
              </span>
            ) : null}
            {shortlisted ? <span className="b-chip b-chip-accent">Shortlisted</span> : null}
            {candidate.invitationStatus ? (
              <span className="b-chip">{candidate.invitationStatus}</span>
            ) : null}
          </span>
          <span className="mt-2 flex items-center gap-3">
            <span className="b-meter w-full max-w-[220px]">
              <span style={{ width: `${percentage}%` }} />
            </span>
            <span className="shrink-0 font-[family-name:var(--font-mono)] text-[0.78rem] text-[var(--text-secondary)]">
              {candidate.score}/{maxScore}
            </span>
          </span>
        </span>

        <span className="hidden shrink-0 text-right sm:block">
          {candidate.quotationTotalCents != null ? (
            <>
              <span className="block font-[family-name:var(--font-mono)] text-[0.85rem] text-[var(--text-primary)]">
                {formatMoney(candidate.quotationTotalCents, "USD")}
              </span>
              <span className="b-eyebrow">{candidate.quotationStatus}</span>
            </>
          ) : (
            <span className="b-eyebrow">No offer yet</span>
          )}
        </span>

        <CaretDown
          size={14}
          className={`shrink-0 text-[var(--text-muted)] transition-transform ${expanded ? "rotate-180" : ""}`}
        />
      </button>

      {expanded ? (
        <div className="border-t border-[var(--b-line)] bg-[var(--b-tint)] px-5 py-4">
          <table className="data-table">
            <thead>
              <tr>
                <th>Criterion</th>
                <th>Assessment</th>
                <th className="num">Points</th>
              </tr>
            </thead>
            <tbody>
              {candidate.breakdown.map((component) => (
                <tr key={component.key}>
                  <td className="text-[var(--text-secondary)]">{component.label}</td>
                  <td className="text-[var(--text-primary)]">{component.note ?? "Not applicable"}</td>
                  <td className="num">
                    {component.points}
                    <span className="text-[var(--text-muted)]">/{component.max}</span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>

          {candidate.invitedAt ? (
            <p className="mt-3 text-[0.75rem] text-[var(--text-muted)]">
              Invited {new Date(candidate.invitedAt).toLocaleString()}
              {candidate.respondedAt ? ` · Responded ${new Date(candidate.respondedAt).toLocaleString()}` : " · Awaiting response"}
            </p>
          ) : null}
        </div>
      ) : null}
    </li>
  );
}

function FunnelCell({ label, value }: { label: string; value: number }) {
  return (
    <div className="bg-[var(--bg-card)] px-4 py-3">
      <p className="b-eyebrow">{label}</p>
      <p className="mt-1 font-[family-name:var(--font-mono)] text-[1.15rem] text-[var(--text-primary)]">{value}</p>
    </div>
  );
}
